# Generated by Django 3.1.2 on 2020-10-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20201023_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deposit_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='return_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
